apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-crud
  labels:
    app: mongo-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-crud
  template:
    metadata:
      labels:
        app: mongo-crud
    spec:
      containers:
      - name: mongo-crud
        image: tonudon86/mongo-crud
        env:
        - name: DEMO_GREETING
          value: "Hello from the environment in kubernetes"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
