apiVersion: v1
kind: Service
metadata:
  name: mongo-crud
spec:
  type: ClusterIP
  selector:
    app: mongo-crud
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
