apiVersion: v1
kind: Service
metadata:
  name: mongo-crud
spec:
  type: LoadBalancer
  selector:
    app: mongo-crud
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 31200
